modLoader="javafml"
loaderVersion="[32,)" #mandatory
issueTrackerURL="https://github.com/Epidra/BetterConnectedGlass/issues"
[[mods]]
modId="connectedglass"
version="v02"
displayName="DoubleConnectedGlass" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/doubleconnectedglass"
logoFile="connectedglass.png"
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
Connects glass Blocks in a different way
'''
[[dependencies.connectedglass]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"