modLoader="javafml"
loaderVersion="[35,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/Epidra/BetterConnectedGlass/issues"
[[mods]]
modId="connectedglass"
version="v03"
displayName="DoubleConnectedGlass" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/doubleconnectedglass"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
Connects glass Blocks in a different way
'''
[[dependencies.connectedglass]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"